//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whirlybird.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsEs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsEs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Whirlybird.Localization.StringsEs", typeof(StringsEs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string amogus {
            get {
                return ResourceManager.GetString("amogus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige tu idioma:.
        /// </summary>
        internal static string choose_language {
            get {
                return ResourceManager.GetString("choose-language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basica.
        /// </summary>
        internal static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar cambios.
        /// </summary>
        internal static string confirm_changes {
            get {
                return ResourceManager.GetString("confirm-changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige el color del cursor.
        /// </summary>
        internal static string cursor_colorpick {
            get {
                return ResourceManager.GetString("cursor-colorpick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garabatear.
        /// </summary>
        internal static string doodle {
            get {
                return ResourceManager.GetString("doodle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanol.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige el color de fuente principal.
        /// </summary>
        internal static string font_colorpick {
            get {
                return ResourceManager.GetString("font-colorpick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresario.
        /// </summary>
        internal static string formal {
            get {
                return ResourceManager.GetString("formal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo dificil.
        /// </summary>
        internal static string hardmode_pick {
            get {
                return ResourceManager.GetString("hardmode-pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejor puntuación:.
        /// </summary>
        internal static string high_score {
            get {
                return ResourceManager.GetString("high-score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca su nombre:.
        /// </summary>
        internal static string input_name_invitation {
            get {
                return ResourceManager.GetString("input-name-invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon de la Fama.
        /// </summary>
        internal static string leaderboard {
            get {
                return ResourceManager.GetString("leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige el color de fondo.
        /// </summary>
        internal static string main_colorpick {
            get {
                return ResourceManager.GetString("main-colorpick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presione &apos;ESC&apos; para regresar al menú.
        /// </summary>
        internal static string menu_invitation {
            get {
                return ResourceManager.GetString("menu-invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin dueno.
        /// </summary>
        internal static string not_owned {
            get {
                return ResourceManager.GetString("not-owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apagada.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedad.
        /// </summary>
        internal static string owned {
            get {
                return ResourceManager.GetString("owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patriotico.
        /// </summary>
        internal static string patriotic {
            get {
                return ResourceManager.GetString("patriotic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESIONE R O HAGA CLIC EN EL RATÓN PARA REINICIAR.
        /// </summary>
        internal static string press_to_restart {
            get {
                return ResourceManager.GetString("press-to-restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rico.
        /// </summary>
        internal static string rich {
            get {
                return ResourceManager.GetString("rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija el color de fuente secundario.
        /// </summary>
        internal static string second_font_colorpick {
            get {
                return ResourceManager.GetString("second-font-colorpick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercio.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMENZAR.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraniano.
        /// </summary>
        internal static string ua {
            get {
                return ResourceManager.GetString("ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al reves.
        /// </summary>
        internal static string upside_down {
            get {
                return ResourceManager.GetString("upside-down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La posicion de su resultado en TOP es.
        /// </summary>
        internal static string your_result {
            get {
                return ResourceManager.GetString("your-result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu puntuacion:.
        /// </summary>
        internal static string your_score {
            get {
                return ResourceManager.GetString("your-score", resourceCulture);
            }
        }
    }
}
